version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: permoda
      POSTGRES_PASSWORD: permoda_pass
      POSTGRES_DB: permoda_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data:
